import { desc, eq, inArray } from "drizzle-orm";
import { ClipboardCheck } from "lucide-react";
import { AdminPageShell } from "@/components/admin-page-shell";
import { db } from "@/db";
import { distributorProfiles, restockOrderItems, restockOrders } from "@/db/schema";
import { dispatchRestockOrder, reviewRestockOrder } from "./actions";

export default async function AdminRestockPage() {
  const requests = await db.select({ id: restockOrders.id, status: restockOrders.status, note: restockOrders.note, distributor: distributorProfiles.businessName }).from(restockOrders).innerJoin(distributorProfiles, eq(distributorProfiles.id, restockOrders.distributorId)).orderBy(desc(restockOrders.createdAt));
  const items = requests.length ? await db.select({ orderId: restockOrderItems.restockOrderId, product: restockOrderItems.productNameSnapshot, quantity: restockOrderItems.requestedQuantity, unit: restockOrderItems.unitSnapshot }).from(restockOrderItems).where(inArray(restockOrderItems.restockOrderId, requests.map((request) => request.id))) : [];
  const summaries = new Map<string, string>();
  items.forEach((item) => summaries.set(item.orderId, `${summaries.get(item.orderId) ? `${summaries.get(item.orderId)}, ` : ""}${item.product} × ${item.quantity} ${item.unit}`));
  return <AdminPageShell action="Restock requests" description="Review distributor restock requests before company warehouse dispatch." icon={ClipboardCheck} label="Restock" title="Restock approvals"><section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="bg-slate-50 text-[10px] font-semibold uppercase tracking-[0.06em] text-slate-500"><tr><th className="px-4 py-3">Request</th><th className="px-4 py-3">Distributor</th><th className="px-4 py-3">Products</th><th className="px-4 py-3">Note</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{requests.length ? requests.map((request) => <tr key={request.id}><td className="border-t border-slate-100 px-4 py-3 font-mono text-xs text-slate-600">{request.id.slice(0, 8)}</td><td className="border-t border-slate-100 px-4 py-3 font-medium text-slate-700">{request.distributor}</td><td className="max-w-90 border-t border-slate-100 px-4 py-3 text-xs text-slate-600">{summaries.get(request.id)}</td><td className="max-w-60 border-t border-slate-100 px-4 py-3 text-xs text-slate-600">{request.note ?? "—"}</td><td className="border-t border-slate-100 px-4 py-3 capitalize text-slate-600">{request.status.replaceAll("_", " ")}</td><td className="border-t border-slate-100 px-4 py-3">{request.status === "submitted" ? <div className="flex gap-2"><form action={reviewRestockOrder}><input name="restockOrderId" type="hidden" value={request.id} /><input name="decision" type="hidden" value="approved" /><button className="h-8 rounded-md bg-slate-900 px-2.5 text-xs font-medium text-white" type="submit">Approve</button></form><form action={reviewRestockOrder}><input name="restockOrderId" type="hidden" value={request.id} /><input name="decision" type="hidden" value="rejected" /><button className="h-8 rounded-md border border-rose-200 px-2.5 text-xs font-medium text-rose-700" type="submit">Reject</button></form></div> : request.status === "approved" ? <form action={dispatchRestockOrder}><input name="restockOrderId" type="hidden" value={request.id} /><button className="h-8 rounded-md border border-slate-300 px-2.5 text-xs font-medium text-slate-700" type="submit">Mark dispatched</button></form> : <span className="text-xs text-slate-400">{request.status === "received" ? "Received" : "Complete"}</span>}</td></tr>) : <tr><td className="border-t border-slate-100 px-4 py-10 text-center text-sm text-slate-500" colSpan={6}>No distributor restock requests yet.</td></tr>}</tbody></table></div></section></AdminPageShell>;
}
