import { desc, eq } from "drizzle-orm";
import { PackagePlus } from "lucide-react";
import { db } from "@/db";
import { products, restockOrders } from "@/db/schema";
import { DataTable, PortalPage } from "../_components/portal-page";
import { formatNaira, getPortalDistributor, statusLabel } from "../_components/data";
import { receiveRestockOrder, submitRestockOrder } from "./actions";

export default async function RestockPage() {
  const distributor = await getPortalDistributor();
  if (!distributor) return null;
  const [catalogue, requests] = await Promise.all([
    db.select({ id: products.id, name: products.name, variant: products.variant, unit: products.unit, price: products.unitPriceKobo, available: products.availableQuantity }).from(products).where(eq(products.isActive, true)),
    db.select({ id: restockOrders.id, status: restockOrders.status, createdAt: restockOrders.createdAt, note: restockOrders.note }).from(restockOrders).where(eq(restockOrders.distributorId, distributor.id)).orderBy(desc(restockOrders.createdAt)),
  ]);
  return <PortalPage description="Request stock from the company warehouse. A company admin must review every request." icon={PackagePlus} title="Restock from company">
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="panel-heading border-b border-slate-200 px-4 py-3"><p className="text-sm font-medium text-slate-700">New restock request</p><p className="mt-1 text-xs text-slate-500">Enter quantities needed for each product, then submit for approval.</p></div><form action={submitRestockOrder} className="p-4"><div className="overflow-x-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="bg-slate-50 text-[10px] font-semibold uppercase tracking-[0.06em] text-slate-500"><tr><th className="px-3 py-2">Product</th><th className="px-3 py-2">Unit</th><th className="px-3 py-2">Price per unit</th><th className="px-3 py-2">Company stock</th><th className="px-3 py-2">Request quantity</th></tr></thead><tbody>{catalogue.map((product) => <tr key={product.id}><td className="border-t border-slate-100 px-3 py-3 font-medium text-slate-700">{product.name}{product.variant ? <span className="ml-1 text-xs font-normal text-slate-500">{product.variant}</span> : null}</td><td className="border-t border-slate-100 px-3 py-3 text-slate-600">{product.unit}</td><td className="border-t border-slate-100 px-3 py-3 font-medium text-slate-800">{formatNaira(product.price)}</td><td className="border-t border-slate-100 px-3 py-3 text-slate-600">{product.available}</td><td className="border-t border-slate-100 px-3 py-3"><input className="h-8 w-28 rounded-md border border-slate-200 px-2 text-sm outline-none focus:border-slate-400" min="0" name={`quantity-${product.id}`} placeholder="0" type="number" /></td></tr>)}</tbody></table></div><label className="mt-4 block text-xs font-medium text-slate-700" htmlFor="restock-note">Note for company (optional)</label><textarea className="mt-2 min-h-20 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-slate-400" id="restock-note" maxLength={500} name="note" placeholder="E.g. needed before next market day" /><button className="mt-4 inline-flex h-9 items-center gap-2 rounded-lg bg-slate-900 px-3 text-xs font-medium text-white hover:bg-slate-800" type="submit"><PackagePlus size={15} />Submit restock request</button></form></section>
    <div className="mt-4"><DataTable headers={["Request", "Submitted", "Status", "Note", "Action"]}>{requests.length ? requests.map((request) => <tr key={request.id}><td className="border-t border-slate-100 px-4 py-3 font-mono text-xs text-slate-600">{request.id.slice(0, 8)}</td><td className="border-t border-slate-100 px-4 py-3 text-slate-600">{new Intl.DateTimeFormat("en-NG", { dateStyle: "medium" }).format(request.createdAt)}</td><td className="border-t border-slate-100 px-4 py-3 capitalize text-slate-600">{statusLabel(request.status)}</td><td className="border-t border-slate-100 px-4 py-3 text-slate-600">{request.note ?? "—"}</td><td className="border-t border-slate-100 px-4 py-3">{request.status === "dispatched" ? <form action={receiveRestockOrder}><input name="restockOrderId" type="hidden" value={request.id} /><button className="h-8 rounded-md bg-slate-900 px-2.5 text-xs font-medium text-white" type="submit">Confirm receipt</button></form> : <span className="text-xs text-slate-400">{request.status === "approved" ? "Awaiting dispatch" : "—"}</span>}</td></tr>) : <tr><td className="border-t border-slate-100 px-4 py-10 text-center text-sm text-slate-500" colSpan={5}>No restock requests submitted yet.</td></tr>}</DataTable></div>
  </PortalPage>;
}
